package br.inatel.rm.view;

import br.inatel.rm.controller.ArduinoSerial;
import br.inatel.rm.controller.SerialRead;

/**
 *
 * @author Samuel
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    private ArduinoSerial arduino = new ArduinoSerial("COM3");

    /* Thread para ler a serial */
    public Principal() {
        initComponents();

        Thread t = new Thread() {

            @Override
            public void run() {
                arduino.initialize();
                
                while (true) {
                    lbl_leitura.setText( arduino.read() );
                }
            }
        };
        t.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_leitura = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_leitura.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbl_leitura.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_leitura.setText(" ");
        lbl_leitura.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_leitura, javax.swing.GroupLayout.DEFAULT_SIZE, 619, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addComponent(lbl_leitura, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(119, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public static void main(String args[]) {

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbl_leitura;
    // End of variables declaration//GEN-END:variables
}
